[connections.postgresql]
dialect = "postgresql"
host = "adops-postgres-us-east1.crcvkuetqx1f.us-east-1.rds.amazonaws.com"
port = 5432
database = "adops"
username = "postgres"
password = "qVxoqr[B*AGU4mx<)5GANna4DXP>"
